sudo: false

env:
  global:
    - DOC_REF: github.com/brendanhay/gogol-doc.git
    - secure: "e8/e9v3up3L8uzoeUiE+u51JXNtY4run3LPPnUD3l5znUCy4ginsW7Eg3NYyuCq8yyI2QdxFZjD/+5+kHJwmIF02u57F6a8YUUsKu15pqIMB+zPsF+3MftNy+R7c4LvZGqEFwJPX1+yFOn41Wtx+7qawSXht4lqD/nLdbI79tPZxX05ApDnPnoNn6725iE61H8lw+DlXttxemRh5OowXfIaOFbGw0WEQ+oZ2UWTdUUTCyQ7OLZp2H0Mzvh22ym09/UWKXGmuYMZ1AxzqnSabSqEIDhx9gWsEf/cmiVjQTbcLh7sB6u5O0vt6puz5002yvl+EUtKQr2KPEimbkykAvHEuZycD79p6k2pqrhib0XVsCmIxiMmOcSQI4EQnjtosTZac8UeZpvaQomue5CGzM123rmKcD76X7VtSNgWmhoucu+Mo8BFW2JWyA5egLpYkKZe04fWbD6wTxco6mm0LgxwwITRAY/6dDrpPwzZjyJ6wvC4zDZ/wAe+gcYupRXSGJlQrHaabxJKxdGdX20TaogaYDWFdAHBCq3x3PDTUT08a2VsSQ76t1HQ1Eu0cOFXKcrPIpW58K1sFeEJgz638RlRHGCT2yIuWJmF/bdXXYRXGo/7Xl8SzptXalwdrcv+xZGTKNwZzqBgdzg5A4ogqiMLUin6VQi+EOALzgKsOuj4="

cache:
  apt: true
  directories:
    - ~/.stack

branches:
  only:
    - master
    - develop

before_install:
    - export PATH=/opt/ghc/$GHCVER/bin:$PATH
    - export PATH=~/.local/bin:$PATH
    - ./script/travis-lifecycle-before_install

install:
    - ./script/travis-lifecycle-install

script:
    - ./script/travis-lifecycle-script

matrix:
  fast_finish: true
  allow_failures:
    # This is due to the constant GHC ExitFailure (-9) that occurs on
    # the non-GCE/container infrastructure.
    - env: GHCVER=7.10.2 LIBRARY=gogol-dfareporting

  include:
    # Below is auto-generated by ./scripts/travis-matrix >> .travis.yml

    # Documentation
    - env: GHCVER=7.10.2 LIBRARY=documentation
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }

    # Core
    - env: GHCVER=7.10.2 LIBRARY=gogol-core
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }

    # Priority
    - env: GHCVER=7.10.2 LIBRARY=gogol-compute
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-drive
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-appengine
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-storage
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-oauth2
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-gmail
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }

    # Remainder
    - env: GHCVER=7.10.2 LIBRARY=gogol-adexchange-buyer
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-adexchange-seller
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-admin-datatransfer
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-admin-directory
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-admin-emailmigration
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-admin-reports
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-adsense
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-adsense-host
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-affiliates
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-analytics
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-android-enterprise
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-android-publisher
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-apps-activity
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-apps-calendar
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-apps-licensing
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-apps-reseller
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-apps-tasks
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-autoscaler
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-bigquery
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-billing
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-blogger
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-books
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-civicinfo
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-classroom
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-container
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-customsearch
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-dataflow
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-datastore
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-debugger
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-deploymentmanager
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-dfareporting
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-discovery
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-dns
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-doubleclick-bids
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-doubleclick-search
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-fitness
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-fonts
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-freebasesearch
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-fusiontables
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-games
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-games-appstate
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-games-configuration
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-games-management
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-genomics
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-groups-migration
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-identity-toolkit
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-latencytest
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-logging
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-maps-coordinate
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-maps-engine
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-mirror
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-monitoring
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-pagespeed
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-partners
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-play-moviespartner
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-plus
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-plus-domains
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-prediction
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-proximitybeacon
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-pubsub
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-qpxexpress
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-replicapool
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-replicapool-updater
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-resourcemanager
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-resourceviews
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-shopping-content
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-siteverification
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-spectrum
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-sqladmin
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-storage-transfer
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-tagmanager
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-taskqueue
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-translate
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-urlshortener
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-useraccounts
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-webmaster-tools
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-youtube
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
    - env: GHCVER=7.10.2 LIBRARY=gogol-youtube-analytics
      addons: { apt: { packages: [ghc-7.10.2], sources: [hvr-ghc] } }
